import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val core_testing: String = "androidx.arch.core:core-testing:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val material3: String = "androidx.compose.material3:material3:_"

    public const val material3_window_size_class: String =
            "androidx.compose.material3:material3-window-size-class:_"

    public const val androidx_compose_material_material: String =
            "androidx.compose.material:material:_"

    public const val material_icons_extended: String =
            "androidx.compose.material:material-icons-extended:_"

    public const val runtime_livedata: String = "androidx.compose.runtime:runtime-livedata:_"

    public const val ui: String = "androidx.compose.ui:ui:_"

    public const val ui_test_junit4: String = "androidx.compose.ui:ui-test-junit4:_"

    public const val ui_test_manifest: String = "androidx.compose.ui:ui-test-manifest:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    public const val ui_util: String = "androidx.compose.ui:ui-util:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val hilt_navigation_compose: String = "androidx.hilt:hilt-navigation-compose:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val navigation_compose: String = "androidx.navigation:navigation-compose:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val lottie_compose: String = "com.airbnb.android:lottie-compose:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val accompanist_placeholder_material: String =
            "com.google.accompanist:accompanist-placeholder-material:_"

    public const val accompanist_systemuicontroller: String =
            "com.google.accompanist:accompanist-systemuicontroller:_"

    public const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    public const val com_google_dagger_hilt_android_gradle_plugin: String =
            "com.google.dagger.hilt.android:com.google.dagger.hilt.android.gradle.plugin:_"

    public const val hilt_android: String = "com.google.dagger:hilt-android:_"

    public const val hilt_android_compiler: String = "com.google.dagger:hilt-android-compiler:_"

    public const val truth: String = "com.google.truth:truth:_"

    public const val timber: String = "com.jakewharton.timber:timber:_"

    public const val moshi: String = "com.squareup.moshi:moshi:_"

    public const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:_"

    public const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:_"

    public const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"
}
